FROM nginx

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/ssl/cas-entertainment.crt /etc/nginx/cas-entertainment.crt
COPY ./nginx/ssl/cas-entertainment.key /etc/nginx/cas-entertainment.key

